---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: look for install at {{ tfctl_install_exe }}
  become: true
  stat:
    path: '{{ tfctl_install_exe }}'
  changed_when: false
  register: tfctl_binary
- when: not tfctl_binary.stat.exists
  block:
    - name: downloading {{ tfctl_url }} to {{ tfctl_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ tfctl_url }}'
        dest: '{{ tfctl_tmp_archive }}'
        checksum: '{{ tfctl_checksum }}'
        mode: 0644
    - name: mkdir {{ tfctl_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ tfctl_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchiving {{ tfctl_tmp_archive }} to {{ tfctl_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ tfctl_tmp_archive }}'
        dest: '{{ tfctl_install_dir }}'
        creates: '{{ tfctl_install_exe }}'
  always:
    - name: rm -f {{ tfctl_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ tfctl_tmp_archive }}'
        state: absent
- name: linking {{ tfctl_link }} to {{ tfctl_install_exe }}
  become: true
  become_user: root
  file:
    src: '{{ tfctl_install_exe }}'
    dest: '{{ tfctl_link }}'
    state: link
